//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeReportV3.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunTogetherWithWindows
        {
            get
            {
                return ((bool)(this["RunTogetherWithWindows"]));
            }
            set
            {
                this["RunTogetherWithWindows"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte FrequencyUpdatingValues
        {
            get
            {
                return ((byte)(this["FrequencyUpdatingValues"]));
            }
            set
            {
                this["FrequencyUpdatingValues"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte SelectionIndexDisplayInSystemTray
        {
            get
            {
                return ((byte)(this["SelectionIndexDisplayInSystemTray"]));
            }
            set
            {
                this["SelectionIndexDisplayInSystemTray"] = value;
            }
        }



        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte TraySystemMode
        {
            get
            {
                return ((byte)(this["TraySystemMode"]));
            }
            set
            {
                this["TraySystemMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToBrowser
        {
            get
            {
                return ((string)(this["PathToBrowser"]));
            }
            set
            {
                this["PathToBrowser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alefsupport.trinfico.ru")]
        public string AddressOfServerIntraService
        {
            get
            {
                return ((string)(this["AddressOfServerIntraService"]));
            }
            set
            {
                this["AddressOfServerIntraService"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("intraservice5.trinfico.ru")]
        public string AddressOfServerIS
        {
            get
            {
                return ((string)(this["AddressOfServerIS"]));
            }
            set
            {
                this["AddressOfServerIS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("itdesk.trinfico.ru")]
        public string AddressOfServerJira
        {
            get
            {
                return ((string)(this["AddressOfServerJira"]));
            }
            set
            {
                this["AddressOfServerJira"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyAboutTasksWithoutЕxecutor
        {
            get
            {
                return ((bool)(this["NotifyAboutTasksWithoutЕxecutor"]));
            }
            set
            {
                this["NotifyAboutTasksWithoutЕxecutor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WAV files (*.wav)|*.wav")]
        public string PathToSoundAlertFile
        {
            get
            {
                return ((string)(this["PathToSoundAlertFile"]));
            }
            set
            {
                this["PathToSoundAlertFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1, -1")]
        public global::System.Drawing.Point MainFormLocation
        {
            get
            {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set
            {
                this["MainFormLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormLocationX
        {
            get
            {
                return (int)this["MainFormLocationX"];
            }
            set
            {
                this["MainFormLocationX"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormLocationY
        {
            get
            {
                return (int)this["MainFormLocationY"];
            }
            set
            {
                this["MainFormLocationY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimeUserTableVisible
        {
            get
            {
                return ((bool)(this["TimeUserTableVisible"]));
            }
            set
            {
                this["TimeUserTableVisible"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StandardPopupNotification
        {
            get
            {
                return ((bool)(this["StandardPopupNotification"]));
            }
            set
            {
                this["StandardPopupNotification"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings
        {
            get
            {
                return ((bool)(this["UpgradeSettings"]));
            }
            set
            {
                this["UpgradeSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PhoneNumbersForSms
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["PhoneNumbersForSms"]));
            }
            set
            {
                this["PhoneNumbersForSms"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DontLostFocusCollapse
        {
            get
            {
                return ((bool)(this["DontLostFocusCollapse"]));
            }
            set
            {
                this["DontLostFocusCollapse"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRAexLuPWzcyTfvFsUjfUYI/q9PjV06BCatIXMz3rDPZgXaS+Y7VQKXuo0HE/WWYciRO+eZ9JqHZ00Ld7" +
            "hwzmYsACiS7cD5HRGrO3X9BFSbz3EqqdPscZW6BhlZZxIscRVBExRwLI7MefULbDjzZ8Bbmq1iuHrww1" +
            "YnakZ2aDhxc6ovisPedj7g31SraCf0o")]
        public string Cral
        {
            get
            {
                return ((string)(this["Cral"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1Httpyiu5oL0CbXY+ufdKpl7Q43A2KfXOiAYFe7UVZND3HGmcvxP9ZodEqTSG5e5L2GDxxnL42VzakHku" +
            "WoOIwpv5eRBm1pvPKb8LvBn2CNAxZkE9M81XZkQm2P2GocQ0dM6KlKt0vmJhEXijPdODKHRE51vqIDFZ" +
            "CZEV86Tq9c7e13nu50vRHdx1XrQAAhDvuYzQd8Nux+n9cPONNrolg==")]
        public string Crpg
        {
            get
            {
                return ((string)(this["Crpg"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fzJXI7FwMqsOBF8NSFB5YyWRDIEk9uRVLKyiXjhHlPTaS9aWAP6Nhv+5rb7Cii8v2dXv5zn6tQKCKORfs" +
            "nORZ6poMt/10gzPcSOPfzfDDP2Pe4SdJluavyiufGxZ4dQqGujH4Hoou3lkqi+FIgZ1ig==")]
        public string Crms
        {
            get
            {
                return ((string)(this["Crms"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Postgre SQL")]
        public string TargetDB
        {
            get
            {
                return ((string)(this["TargetDB"]));
            }
            set
            {
                this["TargetDB"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial;10;по умолчанию")]
        public string ReportFont
        {
            get
            {
                return ((string)(this["ReportFont"]));
            }
            set
            {
                this["ReportFont"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("read_only_user")]
        public string LoginJira
        {
            get
            {
                return ((string)(this["LoginJira"]));
            }
            set
            {
                this["LoginJira"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hit_20251001")]
        public string PasswordJira
        {
            get
            {
                return ((string)(this["PasswordJira"]));
            }
            set
            {
                this["PasswordJira"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JiraSoftwareDB")]
        public string JiraDB
        {
            get
            {
                return ((string)(this["JiraDB"]));
            }
            set
            {
                this["JiraDB"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyIS
        {
            get
            {
                return ((bool)(this["NotifyIS"]));
            }
            set
            {
                this["NotifyIS"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyJira
        {
            get
            {
                return ((bool)(this["NotifyJira"]));
            }
            set
            {
                this["NotifyJira"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyAll
        {
            get
            {
                return ((bool)(this["NotifyAll"]));
            }
            set
            {
                this["NotifyAll"] = value;
            }
        }
    }
}
